workflows:
  android-release:
    name: ByteBeam Android APK
    max_build_duration: 60
    environment:
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - akashchanda27@gmail.com
        notify:
          success: true
          failure: true

  windows-release:
    name: ByteBeam Windows EXE
    max_build_duration: 120
    instance_type: windows_x2
    environment:
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.flutter
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Enable Windows
        script: flutter config --enable-windows-desktop
      - name: Build Windows
        script: flutter build windows --release
    artifacts:
      - build/windows/x64/runner/Release/**
    publishing:
      email:
        recipients:
          - akashchanda27@gmail.com
        notify:
          success: true
          failure: true
